DATABASE_HOST = "localhost"
DATABASE_PORT = 3306
DATABASE_USER = "root"
DATABASE_PASSWORD = "123456"
DATABASE_NAME = "inventory_db"

JWT_SECRET_KEY = "ltZ3KRtWwCYPB1M3HGKXRXLFl5nzkIjE5SYjbVKRN5D40rextx5fRfaYtikWCX8YutQtTa-dhTenq0gz1GiiqA"
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_DAYS = 7
